permalink: /:title/

kramdown:
  auto_ids: false

defaults:
  -
    scope:
      path: ""

    values:
      layout: "default"
      lang: "en"
  -
    scope:
      path: "_posts/fr"

    values:
      lang: "fr"

collections:
  pages:
    output: true
    permalink: /:path/

nav:
  en:
    journal:
      title: "journal"
      url:   "/index.html"
    about:
      title: "about"
      url:   "/about/"
  fr:
    journal:
      title: "journal"
      url:   "/journal/"
    about:
      title: "à propos"
      url:   "/a-propos/"

cat:
  jekyll: "Jekyll"
  pi:     "Raspberry Pi"
  r:      "R"