permalink: /:title/

kramdown:
  auto_ids: false

collections:
  medias:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      lang: "en"
  -
    scope:
      type: "posts"
    values:
      layout: "default"
  -
    scope:
      path: "_posts/fr"
    values:
      lang: "fr"
  -
    scope:
      path: "_posts/fr/pages"
    values:
      type: "pages"
  -
    scope:
      path: "_posts/en/pages"
    values:
      type: "pages"

nav:
  en:
    journal:
      title: "journal"
      url:   "/index.html"
    about:
      title: "about"
      url:   "/about/"
  fr:
    journal:
      title: "journal"
      url:   "/journal/"
    about:
      title: "à propos"
      url:   "/a-propos/"
