permalink: /:title/

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "default"

nav:
  en:
    journal:
      title: "journal"
      url:   "/index.html"
    about:
      title: "about"
      url:   "/about/"
  fr:
    journal:
      title: "journal"
      url:   "/journal/"
    about:
      title: "à propos"
      url:   "/a-propos/"
